-- test_sanity.lua: Framework + mock engine smoke test (Commit 1 verification)

local BASE = debug.getinfo(1, "S").source:match("@(.+[\\/])") or "./"
dofile(BASE .. "framework.lua")
dofile(BASE .. "mock/globals.lua")
dofile(BASE .. "mock/engine.lua")
dofile(BASE .. "mock/gns.lua")

describe("Sanity: framework assertions", function()
    it("assert_eq numbers", function()
        assert_eq(42, 42)
    end)

    it("assert_eq strings", function()
        assert_eq("hello", "hello")
    end)

    it("assert_eq tables deep", function()
        assert_eq({ a = 1, b = { c = 2 } }, { a = 1, b = { c = 2 } })
    end)

    it("assert_neq", function()
        assert_neq(1, 2)
    end)

    it("assert_nil", function()
        assert_nil(nil)
    end)

    it("assert_not_nil", function()
        assert_not_nil(42)
    end)

    it("assert_true", function()
        assert_true(true)
    end)

    it("assert_false", function()
        assert_false(false)
    end)

    it("assert_contains", function()
        assert_contains("hello world", "world")
    end)

    it("assert_error", function()
        assert_error(function() error("boom") end)
    end)
end)

describe("Sanity: vector class", function()
    it("vector() creates zero vector", function()
        local v = vector()
        assert_eq(0, v.x)
        assert_eq(0, v.y)
        assert_eq(0, v.z)
    end)

    it("vector():set(x,y,z) stores values", function()
        local v = vector():set(1.5, 2.5, 3.5)
        assert_eq(1.5, v.x)
        assert_eq(2.5, v.y)
        assert_eq(3.5, v.z)
    end)

    it("vector():set returns self", function()
        local v = vector()
        local ret = v:set(10, 20, 30)
        assert_true(ret == v)
        assert_eq(10, ret.x)
    end)
end)

describe("Sanity: alife() singleton", function()
    before_each(function()
        reset_engine()
    end)

    it("alife() returns non-nil singleton", function()
        assert_not_nil(alife())
    end)

    it("alife() has a metatable with __index as table", function()
        local mt = getmetatable(alife())
        assert_not_nil(mt)
        assert_eq("table", type(mt.__index))
    end)

    it("set_mp_client_mode / mp_client_mode round-trip", function()
        alife():set_mp_client_mode(true)
        assert_true(alife():mp_client_mode())
        alife():set_mp_client_mode(false)
        assert_false(alife():mp_client_mode())
    end)

    it("create() assigns incrementing IDs >= 1000", function()
        local pos = vector():set(0, 0, 0)
        local s1 = alife():create("stalker_bandit", pos, 0, 0)
        local s2 = alife():create("stalker_bandit", pos, 0, 0)
        assert_true(s1.id >= 1000)
        assert_true(s2.id > s1.id)
    end)

    it("create() fires server_entity_on_register synchronously", function()
        local fired = false
        RegisterScriptCallback("server_entity_on_register", function(se_obj)
            fired = true
            assert_not_nil(se_obj)
            assert_eq("bloodsucker_weak", se_obj:section_name())
        end)
        local pos = vector():set(10, 0, 10)
        alife():create("bloodsucker_weak", pos, 5, 5)
        assert_true(fired, "callback should have fired synchronously")
    end)

    it("object() returns the created entity", function()
        local pos = vector():set(5, 5, 5)
        local se = alife():create("stalker_bandit", pos, 1, 1)
        assert_not_nil(alife():object(se.id))
        assert_eq(se.id, alife():object(se.id).id)
    end)

    it("release() removes entity and fires server_entity_on_unregister", function()
        local pos = vector():set(0, 0, 0)
        local se = alife():create("stalker_bandit", pos, 0, 0)
        local id = se.id
        local fired = false
        RegisterScriptCallback("server_entity_on_unregister", function(obj)
            fired = true
        end)
        alife():release(se, true)
        assert_nil(alife():object(id))
        assert_true(fired)
    end)
end)

describe("Sanity: level.*", function()
    before_each(function()
        reset_engine()
    end)

    it("get/set_weather", function()
        level.set_weather("storm", true)
        assert_eq("storm", level.get_weather())
    end)

    it("get/set_game_time", function()
        level.set_game_time(14, 30, 0)
        assert_eq(14, level.get_time_hours())
        assert_eq(30, level.get_time_minutes())
    end)

    it("level.name()", function()
        assert_not_nil(level.name())
    end)
end)

describe("Sanity: gns mock", function()
    before_each(function()
        reset_gns()
    end)

    it("send_reliable captures payload", function()
        gns.send_reliable(1, "ES|id=42|section=stalker_bandit")
        local sent = gns._get_sent_reliable()
        assert_eq(1, #sent)
        assert_eq("ES|id=42|section=stalker_bandit", sent[1].payload)
    end)

    it("send_unreliable captures payload", function()
        gns.send_unreliable(-1, "EP|1,10.0,20.0,30.0,1.0")
        local sent = gns._get_sent_unreliable()
        assert_eq(1, #sent)
    end)

    it("inject_message / poll returns message", function()
        gns._inject_message(1, "WS|preset=storm", 14)
        local msgs = gns.poll()
        assert_eq(1, #msgs)
        assert_eq("WS|preset=storm", msgs[1].data)
    end)

    it("inject_event / poll_events returns event", function()
        gns._inject_event(1, "connected", 2)
        local evts = gns.poll_events()
        assert_eq(1, #evts)
        assert_eq(1, evts[1].event_type)
        assert_eq(2, evts[1].conn_id)
    end)
end)

describe("Sanity: globals", function()
    before_each(function()
        reset_globals()
    end)

    it("time_global() starts at 0", function()
        assert_eq(0, time_global())
    end)

    it("advance_time increments", function()
        advance_time(100)
        assert_eq(100, time_global())
        advance_time(50)
        assert_eq(150, time_global())
    end)

    it("printf captures to log", function()
        clear_log()
        set_verbose(false)
        printf("test %d", 42)
        local log = get_log()
        assert_eq(1, #log)
        assert_contains(log[1], "test 42")
        set_verbose(true)
    end)
end)

summary()
